name: PriceOye Watcher

on:
  schedule:
    # 08:00 UTC & 20:00 UTC = 1 PM & 1 AM PKT
    - cron: '0 8,20 * * *'
  workflow_dispatch: # allow manual runs from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      USER_KEY: ${{ secrets.USER_KEY }}
      APP_TOKEN: ${{ secrets.APP_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python priceoye.py
